#####################################
# @repository   diko316
#####################################
FROM debian:latest

ENV PRODUCT_SOURCE=/opt/app

RUN mkdir -p $PRODUCT_SOURCE

ADD ./tools /opt/app-tools

